name: Deploy Chrome Extension

on:
  push:
    tags:
      - "v*"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies and build extension
        run: |
          zip -r extension.zip ./src

      - name: Deploy to Chrome Web Store
        uses: ajayyy/chrome-webstore-upload@v1
        with:
          client_id: ${{ secrets.CLIENT_ID }}
          client_secret: ${{ secrets.CLIENT_SECRET }}
          refresh_token: ${{ secrets.REFRESH_TOKEN }}
          extension_id: ${{ secrets.EXTENSION_ID }}
          zip: extension.zip
          publish: true
